import Footer from "./components/Footer";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-100">
        <div className="relative mx-auto min-h-screen w-full max-w-sm bg-white">
          <div className="pb-20">{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
